export const TOWER_TIERS = [
  {
    tier: 0,
    name: "Shack",
    minCommits: 0,
    maxCommits: 49,
    material: "wood" as const,
    colorPrimary: "#8B6914",
    colorSecondary: "#6B4F12",
    windowDensity: 0.2,
    hasAntenna: false,
    hasSpire: false,
    hasCrown: false,
    glowIntensity: 0,
    description: "A humble beginning",
  },
  {
    tier: 1,
    name: "Brick Building",
    minCommits: 50,
    maxCommits: 249,
    material: "brick" as const,
    colorPrimary: "#A0522D",
    colorSecondary: "#8B4513",
    windowDensity: 0.4,
    hasAntenna: false,
    hasSpire: false,
    hasCrown: false,
    glowIntensity: 0.1,
    description: "A solid foundation",
  },
  {
    tier: 2,
    name: "Office Tower",
    minCommits: 250,
    maxCommits: 999,
    material: "concrete" as const,
    colorPrimary: "#708090",
    colorSecondary: "#4682B4",
    windowDensity: 0.6,
    hasAntenna: false,
    hasSpire: false,
    hasCrown: false,
    glowIntensity: 0.2,
    description: "Rising through the ranks",
  },
  {
    tier: 3,
    name: "Glass Tower",
    minCommits: 1000,
    maxCommits: 4999,
    material: "glass" as const,
    colorPrimary: "#87CEEB",
    colorSecondary: "#4169E1",
    windowDensity: 0.8,
    hasAntenna: false,
    hasSpire: true,
    hasCrown: false,
    glowIntensity: 0.4,
    description: "A shining achievement",
  },
  {
    tier: 4,
    name: "Skyscraper",
    minCommits: 5000,
    maxCommits: 9999,
    material: "chrome" as const,
    colorPrimary: "#C0C0C0",
    colorSecondary: "#FFD700",
    windowDensity: 0.9,
    hasAntenna: true,
    hasSpire: true,
    hasCrown: true,
    glowIntensity: 0.6,
    description: "Touching the clouds",
  },
  {
    tier: 5,
    name: "Futuristic Tower",
    minCommits: 10000,
    maxCommits: Infinity,
    material: "holographic" as const,
    colorPrimary: "#00FFFF",
    colorSecondary: "#FF00FF",
    windowDensity: 1.0,
    hasAntenna: true,
    hasSpire: true,
    hasCrown: true,
    glowIntensity: 1.0,
    description: "Beyond imagination",
  },
] as const;

export const GITHUB_ACHIEVEMENTS = {
  ARCTIC_CODE_VAULT: {
    name: "Arctic Code Vault Contributor",
    description: "Contributed to a repo in the 2020 GitHub Archive Program",
    maxTiers: 1,
    effect: "frost",
    color: "#00BFFF",
  },
  PULL_SHARK: {
    name: "Pull Shark",
    description: "Opened pull requests that were merged",
    maxTiers: 3,
    effect: "shark",
    color: "#1E90FF",
  },
  GALAXY_BRAIN: {
    name: "Galaxy Brain",
    description: "Answers marked as accepted in Discussions",
    maxTiers: 3,
    effect: "nebula",
    color: "#9B59B6",
  },
  YOLO: {
    name: "YOLO",
    description: "Merged a PR without code review",
    maxTiers: 1,
    effect: "fire",
    color: "#FF4500",
  },
  PAIR_EXTRAORDINAIRE: {
    name: "Pair Extraordinaire",
    description: "Co-authored commits on merged PRs",
    maxTiers: 3,
    effect: "orbs",
    color: "#FFD700",
  },
  QUICKDRAW: {
    name: "Quickdraw",
    description: "Closed an issue/PR within 5 minutes of opening",
    maxTiers: 1,
    effect: "lightning",
    color: "#FFFF00",
  },
  STARSTRUCK: {
    name: "Starstruck",
    description: "Owns a repo with many stars",
    maxTiers: 3,
    effect: "stars",
    color: "#FFD700",
  },
} as const;

export type AchievementKey = keyof typeof GITHUB_ACHIEVEMENTS;

export const NEARBY_RADIUS_METERS = 5000;
export const LOCATION_UPDATE_INTERVAL_MS = 30000;
export const SYNC_COOLDOWN_HOURS = 24;
